sudo: required
services:
  - docker
language: python
env:
  global:
    # Deis
    - DEIS_PROD_APPLICATION=cloudflare-datadog-sync
    - DEIS_USERNAME=travis
    - DEIS_CONTROLLER_US_WEST=https://deis.portland.moz.works

    # Docker
    - DOCKER_REPOSITORY=mozmeao/cloudflare-datadog
    - DOCKER_USERNAME="moztravis"
before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
install:
  - pip install flake8
before_script:
  - env > .env
script:
  - flake8 .
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} --pull=true .
deploy:
  - provider: script
    script: bin/push-to-dockerhub.sh
    on:
      branch: master
      repo: mozmeao/cloudflare-datadog
  - provider: script
    script: bin/deploy-travis.sh $DEIS_CONTROLLER_US_WEST $DEIS_PROD_APPLICATION
    on:
      tags: true
      repo: mozmeao/cloudflare-datadog
      condition: $(echo ${TRAVIS_TAG} | egrep "^201[6-9][0-9]{4}.[0-9]+")
