sudo: required
services:
  - docker
language: python
env:
  global:
    # Deis
    - DEIS_PROD_APPLICATION=cloudflare-datadog-sync
    - DEIS_USERNAME=travis
    - DEIS_CONTROLLER_US_WEST=https://deis.us-west.moz.works

    # Docker
    - DOCKER_REPOSITORY=mozorg/cloudflare-datadog-sync
    - DOCKER_USERNAME="mozjenkins"
before_install:
  - docker --version
  - echo "ENV GIT_SHA ${TRAVIS_COMMIT}" >> Dockerfile
before_script:
  - env > .env
install:
  # Take advantage of docker caching by pulling previously built images.
  - docker pull ${DOCKER_REPOSITORY}:latest || true
  - docker pull ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} || true
script:
  - docker build -t ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} --pull=true .
deploy:
  - provider: script
    script: bin/deploy-travis.sh $DEIS_CONTROLLER_US_WEST $DEIS_PROD_APPLICATION
    on:
      tags: true
      repo: mozmar/cloudflare-datadog
      condition: $(echo ${TRAVIS_TAG} | egrep "^201[6-9][0-9]{4}.[0-9]+")
